version: '3.8'

networks:
  kek:

services:
  rjd_database:
    image: postgres:15-alpine
    container_name: rjd_database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rjd
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data_rjd:/var/lib/postgresql/data
    networks:
      - kek

  rjd-server:
    build: .
    container_name: server
    ports:
      - "3000:3000"
    depends_on:
      - rjd_database
    restart: unless-stopped
    networks:
      - kek


volumes:
  postgres_data_rjd: