version: '3.8'

services:
  rjd_database:
    image: postgres:15-alpine
    container_name: rjd_database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rjd
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres_data_rjd:/var/lib/postgresql/data

volumes:
  postgres_data_rjd: